# Basic Operations in opencv for digital image processing
### objectives :
  * What is an image?
  * Binary representation of image?
  * Most of the definition I wrote is my own so don't stick to it
  
  ```
  pip install opencv-python
  ```
  

####  Greyscale  Image is noting but a two dimensional array of numbers in range between [0,255]


We use :
* #### cv2.imread() for reading an image  
* #### cv2.imshow() for showing an image
* #### In grey scale pixels are in range of 0-255 here 0 means black color and 255 means white color
* #### Remaining numbers  varies the intensities of black and white


In [1]:
import cv2 as cv

In [2]:
#image is just a number in range 0-255
#So here cv.imread is used to load the read the image
img = cv.imread("temp.jpg", 0)
type(img)
print(img)

[[ 74  74  74 ...  80  80  80]
 [ 74  74  74 ...  80  80  80]
 [ 74  74  74 ...  80  80  80]
 ...
 [181 180 178 ... 233 233 233]
 [182 182 181 ... 226 226 226]
 [182 182 181 ... 221 221 221]]


For the purpose  generating  an img with 200*200 total 40000 pixels .
So we use random in numpy 

In [3]:
#now lets have some fun lets create a random image using numpy
import numpy as np

#for the purpose of radomly genarating an img with 200*200 total 40000 pixcels
# randint(rang,(size))
random_img = np.random.randint(255, size=(200, 200), dtype=np.uint8)
print(random_img)
#this picture is random noise
cv.imshow("sd", random_img)
cv.waitKey(0)
cv.destroyAllWindows()

[[151 240  46 ...  45 201 201]
 [142 166   3 ... 150 189  86]
 [ 41 212  29 ... 120 195  86]
 ...
 [101 100  36 ... 114  68 248]
 [ 65  40 163 ... 141  58  57]
 [ 67 176 154 ...  91 118  91]]


In [6]:
#image,color
#1 means load color image
#0 means load grayscale image
#Loads image as such including alpha channel
img1 = cv.imread("temp.jpg", 0)
img2 = cv.imread("temp.jpg", 1)
img3 = cv.imread("temp.jpg", -1)

cv.imshow("img", img1)
cv.imshow("img1", img2)
cv.imshow("img2", img3)

cv.waitKey(0)
cv.destroyAllWindows()

### From till now we learn about imshow and imread now lets look at another function imwrite 
### I think  you all guess what it dose .
### It just write the image into a new Image 
#### syntax:
```
cv2.imwrite(filename,img)
```

In [5]:
#read image
img = cv.imread("temp.jpg", 0)
#show the image
cv.imshow("image", img)
#now write the image
cv.imwrite("new_temp.jpg", img)

#it is the new image which is just saved in your current directory
writes_img = cv.imread("new_temp.jpg", 0)
cv.imshow("newly writed image", writes_img)

cv.waitKey(0)
cv.destroyAllWindows()

### These are the basic operation we use more often in DIP next here 
#### There is another one which I used at end of every cell execution 
```
cv.waitKey(0)
cv.destroyAllWindows()
```
#### Here cv2.waitKey(0) means It wait the image view until the user hit  a key from keyboard (or) click on close symbol
#### cv.destroyAllWindows() is used for if user hit a key from keyboard it will close all the image views 
#### Lets see an example on these two instructions 👇

In [9]:
dhoni_img = cv.imread("dhoni.jpg",1)
cv.imshow("dhoni",dhoni_img)

key_pressed = cv.waitKey(0)
print(key_pressed)
if(key_pressed== ord('c')):
    cv.destroyAllWindows()
    print("All tabs are closed")

101


> Thank  you if your interested add more examples to this notebook .
> Please Ignore my notebook if I mention anything wrong .Feel free to mention it in comment section.Modifications and contributions are appreciated
